services:
  - type: web
    name: aicomply-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://neondb_owner:npg_3spCxQkgB4Ie@ep-late-fog-at6lp3bp-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        value: 119d6690c14481f044cd71777b224483be694ebce30b6d3ecf02a3ecc3d4af07
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: '["*"]'
      - key: PYTHON_VERSION
        value: 3.12.0
